const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Teaches the generated android/app/build.gradle to sign release builds with
 * the real Play upload key instead of the debug keystore it defaults to.
 *
 * This has to be a config plugin rather than a hand edit: android/ is
 * generated by `expo prebuild` and gitignored, so any direct edit is silently
 * lost the next time it's regenerated -- and the failure mode of that is a
 * release build that looks fine but is debug-signed, which Play rejects on
 * upload.
 *
 * The credentials are never stored in the repo. Gradle reads them from
 * properties, which belong in %USERPROFILE%\.gradle\gradle.properties:
 *
 *   NGHOME_UPLOAD_STORE_FILE=D:\\path\\to\\upload-keystore.jks
 *   NGHOME_UPLOAD_STORE_PASSWORD=...
 *   NGHOME_UPLOAD_KEY_ALIAS=...
 *   NGHOME_UPLOAD_KEY_PASSWORD=...
 *
 * When those properties are absent the release build falls back to debug
 * signing, so a plain `./gradlew bundleRelease` still works for anyone
 * without the keystore -- useful for checking things like native library
 * page alignment, which don't care who signed the bundle.
 */

const SIGNING_CONFIGS_ANCHOR = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;

const SIGNING_CONFIGS_REPLACEMENT = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('NGHOME_UPLOAD_STORE_FILE')) {
                storeFile file(NGHOME_UPLOAD_STORE_FILE)
                storePassword NGHOME_UPLOAD_STORE_PASSWORD
                keyAlias NGHOME_UPLOAD_KEY_ALIAS
                keyPassword NGHOME_UPLOAD_KEY_PASSWORD
            }
        }
    }`;

const RELEASE_BUILDTYPE_ANCHOR = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_BUILDTYPE_REPLACEMENT = `            // Signed with the Play upload key when its properties are present
            // (see plugins/withReleaseSigning.js); debug-signed otherwise, so
            // a build without the keystore still succeeds.
            signingConfig project.hasProperty('NGHOME_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    // Fail loudly rather than quietly emitting a debug-signed release: if the
    // Expo template changes shape, we want the build to stop here, not to
    // discover it when Play rejects the upload.
    if (!gradle.includes(SIGNING_CONFIGS_ANCHOR)) {
      throw new Error(
        'withReleaseSigning: could not find the debug signingConfigs block in ' +
          'app/build.gradle. The Expo template likely changed -- update the ' +
          'anchor in plugins/withReleaseSigning.js.',
      );
    }
    if (!gradle.includes(RELEASE_BUILDTYPE_ANCHOR)) {
      throw new Error(
        'withReleaseSigning: could not find the release buildType signingConfig ' +
          'line in app/build.gradle. The Expo template likely changed -- update ' +
          'the anchor in plugins/withReleaseSigning.js.',
      );
    }

    gradle = gradle.replace(SIGNING_CONFIGS_ANCHOR, SIGNING_CONFIGS_REPLACEMENT);
    gradle = gradle.replace(RELEASE_BUILDTYPE_ANCHOR, RELEASE_BUILDTYPE_REPLACEMENT);

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
